---
- name: installing and launching filebeat
  hosts: webservers
  become: yes
  tasks:

  - name: delete wrong filebeat.yml
    ansible.builtin.file:
      path: /etc/filebeat/filebeat.yml
      state: absent

  - name: download filebeat deb
    get_url:
      url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb
      dest: /home/azadmin/

  - name: install filebeat deb
    command: dpkg -i filebeat-7.6.1-amd64.deb

  - name: drop in filebeat.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: filebeat module to enable filebeat
    command: filebeat modules enable system

  - name: setup filebeat
    command: filebeat setup -e

  - name: start filebeat service
    ansible.builtin.service:
      name: filebeat
      state: started

  - name: enable service filebeat on boot
    systemd:
      state: started
      enabled: yes
      name: filebeat