---
- name: installing and launching metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: download metricbeat deb
    get_url:
      url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
      dest: /home/azadmin/

  - name: drop in metricbeat.yml
    copy:
      src: /etc/ansible/files/metricbeat--config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: install metricbeat deb
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: metricbeat module to enable meticebeat
    command: metricbeat modules enable docker

  - name: setup metricbeat
    command: metricbeat setup -e

  - name: start metricbeat service
    ansible.builtin.service:
      name: metricbeat
      state: started

  - name: enable service metricbeat on boot
    systemd:
      state: started
      enabled: yes
      name: metricbeat